# **Non Graded Challenge 9 (Phase 0)**

## **Objective:**

This Non Graded Challenge was created to evaluate the concept and practical of web scraping with the aim of:

1. Able to explore the elements of a website
2. Able to scrape data from a website

### **Task 1**

Scrape coins price from https://coinmarketcap.com/ with following requirements:

*    Scrape up to 1000 coins

*    Including Price, Market Cap, Volume, and Coin supply

*    Save into Pandas DataFrame and then save into excel or csv file4

The task is to get information about Price, Market Cap, Volume, and Coin supply.

Based on the Inspect element, we know that those information locate on:
- Price: ```<div class="sc-b3fc6b7-0 dzgUIj"><span>$63,726.87</span></div>``` 
- Market Cap: ```<span data-nosnippet="true" class="sc-11478e5d-1 jfwGHx">$1,258,491,567,492</span></p>```
- Volume: ```<p font-size="1" class="sc-71024e3e-0 bbHOdE font_weight_500" color="text" data-sensors-click="true">$40,855,511,985</p>```
- Coin Supply: ```<p font-size="1" font-weight="medium" color="text" data-sensors-click="true" class="sc-71024e3e-0 hhmVNu">19,756,443 BTC</p>```

In [151]:
from bs4 import BeautifulSoup
from selenium import webdriver
import requests
import pandas as pd

page = requests.get("https://coinmarketcap.com/?page")
page

# Create an instance of the Chrome browser
driver = webdriver.Chrome()

# Open the URL
url = "https://coinmarketcap.com/?page=1"
driver.get(url)

# Extract the HTML content
html = driver.page_source

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

In [152]:
# Price
price = soup.find_all('div',{"class":"sc-b3fc6b7-0 dzgUIj"})
for p in price:
    print(p.get_text())

$63,415.42
$2,553.40
$1.00
$572.95
$150.80
$0.9999
$0.5853
$0.1064
$5.69
$0.1525
$0.3582
$28.15
$0.00001438
$11.66

In [153]:
# Market Cap
market_cap = soup.find_all('span',{"class":"sc-11478e5d-1 jfwGHx"})
for cap in market_cap:
    print(cap.get_text())

$1,252,582,161,523
$307,244,603,509
$119,079,316,058
$83,612,052,491
$70,649,070,369
$35,543,982,391
$33,028,921,381
$15,536,535,109
$14,417,380,229
$13,214,910,543
$12,879,754,706
$11,427,150,112
$8,472,913,363
$7,093,216,667

In [154]:
# Volume
volume = soup.find_all('p',{"class":"sc-71024e3e-0 bbHOdE font_weight_500"})
for vol in volume:
    print(vol.get_text())

$39,849,998,174
$19,589,344,400
$67,777,108,456
$1,918,642,088
$3,273,070,688
$6,625,000,556
$1,282,895,785
$654,933,962
$255,981,104
$303,702,450
$284,960,402
$491,721,501
$230,624,456
$273,352,764

In [155]:
#Coin Supply
coin_supply = soup.find_all('p',{"class":"sc-71024e3e-0 hhmVNu"})
for coins in coin_supply:
    print(coins.get_text())

19,756,596 BTC
120,345,933 ETH
119,072,842,113 USDT
145,933,675 BNB
468,491,168 SOL
35,547,497,321 USDC
56,434,507,880 XRP
146,034,616,384 DOGE
2,532,635,424 TON
86,673,608,568 TRX
35,960,643,044 ADA
405,954,810 AVAX
589,269,506,497,063 SHIB
608,099,970 LINK

In [159]:
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import time

# Create an instance of the Chrome browser
driver = webdriver.Chrome()

# Open the URL
url = "https://coinmarketcap.com/?page=1"
driver.get(url)

# Let the page load
time.sleep(10)

for _ in range(10):
    # Scroll down by a fixed amount (to simulate continuous scrolling)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

    # Wait for new coins to load
    time.sleep(10)

# The full page should be loaded now, extract the HTML content
html = driver.page_source

# Parse the HTML content using BeautifulSoup
soup = BeautifulSoup(html, "html.parser")

# Extract coin data
names = [name.get_text() for name in soup.find_all('p', {"class": "sc-71024e3e-0 ehyBa-d"})]
prices = [p.get_text() for p in soup.find_all('div', {"class": "sc-b3fc6b7-0 dzgUIj"})]
market_caps = [market_cap.get_text() for market_cap in soup.find_all('span', {"class": "sc-11478e5d-1 jfwGHx"})]
volumes = [volume.get_text() for volume in soup.find_all('p', {"class": "sc-71024e3e-0 bbHOdE font_weight_500"})]
coin_supplies = [coin_supply.get_text() for coin_supply in soup.find_all('p', {"class": "sc-71024e3e-0 hhmVNu"})]

# Check the length of each list
print(f"Names: {len(names)}, Prices: {len(prices)}, Market Caps: {len(market_caps)}, Volumes: {len(volumes)}, Coin Supplies: {len(coin_supplies)}")

# Find the maximum length among all lists
max_len = max(len(names), len(prices), len(market_caps), len(volumes), len(coin_supplies))

# To make sure all lists have the same length, filling missing values with None
names += [None] * (max_len - len(names))
prices += [None] * (max_len - len(prices))
market_caps += [None] * (max_len - len(market_caps))
volumes += [None] * (max_len - len(volumes))
coin_supplies += [None] * (max_len - len(coin_supplies))

# Create a DataFrame
data = pd.DataFrame({
    'Name': names,
    'Price': prices,
    'Market Cap': market_caps,
    'Volume': volumes,
    'Coin Supply': coin_supplies
})

# Display the scraped data
data

Names: 33, Prices: 21, Market Caps: 21, Volumes: 21, Coin Supplies: 21

,Name,Price,Market Cap,Volume,Coin Supply
0,Bitcoin,"$63,016.70","$1,244,996,539,515","$39,495,003,922","19,756,612 BTC"
1,Super Trump Coin,"$2,541.20","$305,823,189,766","$19,506,509,574","120,345,933 ETH"
2,Baby Doge Coin,$1.00,"$119,093,208,151","$67,488,296,031","119,072,842,113 USDT"
3,RUNEVM,$572.04,"$83,479,836,490","$1,905,288,697","145,933,675 BNB"
4,XBorg,$150.40,"$70,460,835,179","$3,247,121,317","468,491,168 SOL"
5,Neiro 2.0,$1.00,"$35,550,069,180","$6,595,679,590","35,547,497,321 USDC"
6,Wrapped Dog,$0.5839,"$32,951,466,016","$1,276,753,285","56,434,507,880 XRP"
7,Data Ownership Protocol,$0.1064,"$15,541,911,923","$650,306,341","146,034,616,384 DOGE"
8,BlackCardCoin,$5.69,"$14,411,959,881","$254,380,918","2,532,635,424 TON"
9,Bitcoin,$0.1523,"$13,203,035,772","$302,740,471","86,673,608,568 TRX"
10,Super Trump Coin,$0.3579,"$12,870,381,463","$282,949,919","35,960,643,044 ADA"
11,Baby Doge Coin,$28.09,"$11,401,720,309","$490,159,733","405,954,810 AVAX"
12,Bitcoin,$0.00001434,"$8,449,337,676","$228,538,927","589,269,506,497,063 SHIB"
13,Ethereum,$11.67,"$7,095,437,436","$271,076,563","608,099,970 LINK"
14,Tether,$0.1473,"$652,767,592","$25,676,731","4,432,378,861 CFX"
15,BNB,$0.00003281,"$648,362,339","$11,891,696","19,759,404,673,090 XEC"
16,Solana,"$2,609.13","$643,214,375","$5,662,674","246,524 XAUt"
17,USDC,$0.2712,"$633,484,409","$45,270,931","2,336,232,126 SAND"
18,XRP,$0.2437,"$628,160,761","$53,322,525","2,577,873,594 W"
19,Dogecoin,$0.0002945,"$618,543,652","$123,350,667","2,100,000,000,000 1000SATS"
20,Toncoin,$18.44,"$609,992,484","$91,902,489","33,085,239 ENS"
21,TRON,None,None,None,None
22,Cardano,None,None,None,None
23,Avalanche,None,None,None,None
24,Shiba Inu,None,None,None,None
25,Chainlink,None,None,None,None
26,Conflux,None,None,None,None
27,eCash,None,None,None,None
28,Tether Gold,None,None,None,None
29,The Sandbox,None,None,None,None
30,Wormhole,None,None,None,None
31,SATS,None,None,None,None
32,Ethereum Name Service,None,None,None,None

In [166]:
# Initialize lists
prices_list = []
market_caps_list = []
volumes_list = []
coin_supplies_list = []

for i in range(50):
    url = f"https://coinmarketcap.com/?page={str(i+1)}"

    driver.get(url)

    # Page load
    time.sleep(5)

    for _ in range(10):
        # Scroll down
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")

        # Wait for new coins to load
        time.sleep(5)

    # Saving the page_source
    html = driver.page_source

    soup = BeautifulSoup(html, "html.parser")

    # Extract data for each coin on the page and extend to the lists
    prices_list += [price.get_text() if price else None for price in soup.find_all('div', {"class": "sc-b3fc6b7-0 dzgUIj"})]
    market_caps_list += [market_cap.get_text() if market_cap else None for market_cap in soup.find_all('span', {"class": "sc-11478e5d-1 jfwGHx"})]
    volumes_list += [volume.get_text() if volume else None for volume in soup.find_all('p', {"class": "sc-71024e3e-0 bbHOdE font_weight_500"})]
    coin_supplies_list += [coin_supply.get_text() if coin_supply else None for coin_supply in soup.find_all('p', {"class": "sc-71024e3e-0 hhmVNu"})]

In [168]:
print(f"Prices: {len(prices_list)}, Market Caps: {len(market_caps_list)}, Volumes: {len(volumes_list)}, Coin Supplies: {len(coin_supplies_list)}")

# Find the maximum length among all lists
max_len = max(len(prices_list), len(market_caps_list), len(volumes_list), len(coin_supplies_list))

# Create a DataFrame from the lists
data = pd.DataFrame({
    'Price': prices_list,
    'Market Cap': market_caps_list,
    'Volume': volumes_list,
    'Coin Supply': coin_supplies_list
})

# Display the scraped data
data

Prices: 702, Market Caps: 702, Volumes: 702, Coin Supplies: 702

          Price          Market Cap           Volume           Coin Supply
0    $62,969.01  $1,244,056,032,420  $39,171,837,838        19,756,640 BTC
1     $2,538.90    $305,545,794,436  $20,310,478,689       120,345,933 ETH
2         $1.00    $119,075,717,271  $68,061,577,057  119,072,842,113 USDT
3       $567.51     $82,819,532,828   $1,892,285,346       145,933,665 BNB
4       $147.39     $69,053,097,180   $3,498,113,563       468,490,791 SOL
..          ...                 ...              ...                   ...
697   $0.081028                None             None                  None
698   $0.081028                None             None                  None
699   $0.002952                None             None                  None
700   $0.000154                None             None                  None
701    $0.00131                None             None                  None

[702 rows x 4 columns]

In [169]:
'''
# Extract data for each coin on the page and append to respective lists
prices_list.extend([price.get_text() for price in soup.find_all('div', {"class": "sc-b3fc6b7-0 dzgUIj"})])
market_caps_list.extend([market_cap.get_text() for market_cap in soup.find_all('span', {"class": "sc-11478e5d-1 jfwGHx"})])
volumes_list.extend([volume.get_text() for volume in soup.find_all('p', {"class": "sc-71024e3e-0 bbHOdE font_weight_500"})])
coin_supplies_list.extend([coin_supply.get_text() for coin_supply in soup.find_all('p', {"class": "sc-71024e3e-0 hhmVNu"})])
'''

'\n# Extract data for each coin on the page and append to respective lists\nprices_list.extend([price.get_text() for price in soup.find_all(\'div\', {"class": "sc-b3fc6b7-0 dzgUIj"})])\nmarket_caps_list.extend([market_cap.get_text() for market_cap in soup.find_all(\'span\', {"class": "sc-11478e5d-1 jfwGHx"})])\nvolumes_list.extend([volume.get_text() for volume in soup.find_all(\'p\', {"class": "sc-71024e3e-0 bbHOdE font_weight_500"})])\ncoin_supplies_list.extend([coin_supply.get_text() for coin_supply in soup.find_all(\'p\', {"class": "sc-71024e3e-0 hhmVNu"})])\n'

### **Task 2**

Get weather data from 54 locations in Indonesia from https://www.timeanddate.com/weather/indonesia. 

You should include the information of:

*   Temperature
*   Feels Like
*   Wind Speed
*   Wind Direction
*   Humidity
*   Dew Point
*   Visibility
*   Probability of Rain
*   Amount of Rain

Only take the closest day and time (morning/evening) from the time you do this task

Save into Pandas DataFrame and then save into excel or csv file

In [ ]:
page_2 = requests.get("https://www.timeanddate.com/weather/indonesia")
page_2

In [ ]:
url_2 = "https://www.timeanddate.com/weather/indonesia"
driver.get(url_2)

page = requests.get("https://www.timeanddate.com/weather/indonesia")
page