# **Non Graded Challenge 6 (Phase 0)**

## **Objective:**
This Non Graded Challenge was created to evaluate the concept of Data Wrangling in SQL  with the aim of:
1.   Able to use the SELECT, FROM, and WHERE keywords to get data from a specific column
2.   Able to Explore the table schema.

# **Task**
Create a query to answer the following questions:


*   How many tables are in the `austin_bikeshare` dataset?
*   How many columns in the `bikeshare_stations` table have `STRING` data?

Create a query to filter data based on the following conditions:

*   Retrieve all trips where the bike_id is not null and the duration is greater than 1000 minutes.
*   Filter trips where the trip_id is "`Walk Up`" and the end_station_name  is "`Stolen`".

### **Install the google-cloud-bigquery library in Colab**

In [4]:
!pip install --upgrade google-cloud-bigquery

Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.10/dist-packages (3.25.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery) (2.19.1)
Requirement already satisfied: google-auth<3.0.0dev,>=2.14.1 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.27.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.4.1)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.7.1)
Requirement already satisfied: packaging>=20.0.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (24.1)
Requirement already satisfied: python-dateutil<3.0dev,>=2.7.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.8.2)
Requirement already satisfied: requests<3.0.0dev,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from google-cloud-bigquery) (2.31.0)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery) (1.63.2)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery) (3.20.3)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery) (1.24.0)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery) (1.64.1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-bigquery) (1.48.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0.0dev,>=2.14.1->google-cloud-bigquery) (5.4.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0.0dev,>=2.14.1->google-cloud-bigquery) (0.4.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth<3.0.0dev,>=2.14.1->google-cloud-bigquery) (4.9)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.10/dist-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery) (1.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil<3.0dev,>=2.7.2->google-cloud-bigquery) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0dev,>=2.21.0->google-cloud-bigquery) (2024.7.4)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=2.14.1->google-cloud-bigquery) (0.6.0)

### **Authenticate and set up Google Cloud credentials**

In [5]:
from google.colab import auth
from google.cloud import bigquery
import pandas as pd

auth.authenticate_user()

### **Set project ID**

In [6]:
project_id = "latihan-2-435409"
client = bigquery.Client(project=project_id)

### **Query your BigQuery database**

In [16]:
# put your query here
query = """
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
"""

# Set up the query
query_job = client.query(query)
query_job = query_job.to_dataframe()
query_job

,trip_id,subscriber_type,bike_id,bike_type,start_time,start_station_id,start_station_name,end_station_id,end_station_name,duration_minutes
0,4098766,24 Hour Walk Up Pass,306,classic,2015-03-12 22:20:09+00:00,2546,ACC - West & 12th Street,2546,ACC - West & 12th Street,47
1,4073980,24 Hour Walk Up Pass,24,classic,2015-03-10 16:10:57+00:00,2545,ACC - Rio Grande & 12th,2546,ACC - West & 12th Street,24
2,4055367,24 Hour Walk Up Pass,862,classic,2015-03-07 19:55:41+00:00,2536,Waller & 6th St.,2568,East 11th/Victory Grill,8
3,4009457,Local365,142,classic,2015-02-27 11:21:15+00:00,2823,East 5th/Broadway @ Capital Metro HQ,2536,Waller & 6th St.,13
4,3988275,24 Hour Walk Up Pass,440,classic,2015-02-21 21:33:51+00:00,2546,ACC - West & 12th Street,2546,ACC - West & 12th Street,45
...,...,...,...,...,...,...,...,...,...,...
2271148,32428108,Local31,16828,electric,2024-02-06 23:49:25+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,22
2271149,32587422,Explorer,21884,electric,2024-02-27 22:25:33+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,2
2271150,32490790,Student Membership,16276,electric,2024-02-15 15:10:24+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,86
2271151,32494577,Student Membership,18564,electric,2024-02-15 23:43:45+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,482
2271152,32503143,Student Membership,22581,electric,2024-02-17 13:49:15+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,10

### **How many tables are in the `austin_bikeshare` dataset?**

**To know the number of tables**

In [72]:
query_tablecount = """
SELECT COUNT(*) AS table_count
FROM `bigquery-public-data.austin_bikeshare.INFORMATION_SCHEMA.TABLES`
"""

In [58]:
query_job2 = client.query(query_tablecount)

In [59]:
result = query_job2.result().to_dataframe()
print(result)

   table_count
0            2

**ATAU**

In [56]:
query_table_details = """
SELECT
  table_catalog, table_schema, table_name, table_type,
  is_insertable_into, creation_time, ddl
FROM
  `bigquery-public-data.austin_bikeshare.INFORMATION_SCHEMA.TABLES`
"""

query_job1 = client.query(query_table_details)
result = query_job1.result().to_dataframe()
print(result)

          table_catalog      table_schema          table_name  table_type  \
0  bigquery-public-data  austin_bikeshare  bikeshare_stations  BASE TABLE
1  bigquery-public-data  austin_bikeshare     bikeshare_trips       CLONE

  is_insertable_into                    creation_time  \
0                YES 2017-05-25 03:43:34.344000+00:00
1                YES 2023-07-17 16:41:33.433000+00:00

                                                 ddl
0  CREATE TABLE `bigquery-public-data.austin_bike...
1  CREATE TABLE `bigquery-public-data.austin_bike...

**To know the table names**

In [60]:
query_tablenames = """
SELECT table_name
FROM `bigquery-public-data.austin_bikeshare.INFORMATION_SCHEMA.TABLES`
"""

In [61]:
query_job3 = client.query(query_tablenames)

In [62]:
result = query_job3.result().to_dataframe()
print(result)

           table_name
0  bikeshare_stations
1     bikeshare_trips

### **How many columns in the `bikeshare_stations` table have `STRING` data?**

In [71]:
query_string_col = """
SELECT
    COUNT(*) AS string_column
    -- EXCEPT(is_generated, generation_expression, is_stored, is_updatable)
  FROM
    `bigquery-public-data`.austin_bikeshare.INFORMATION_SCHEMA.COLUMNS
  WHERE
    table_name = 'bikeshare_stations' AND data_type = 'STRING'
"""

query_job4 = client.query(query_string_col)
result = query_job4.result().to_dataframe()
print(result)

   string_column
0              7

### **Retrieve all trips where the `bike_id` is `not null` and the `duration` is greater than 1000 minutes**

In [73]:
# Melihat tabel bikeshare_trips
query_job

,trip_id,subscriber_type,bike_id,bike_type,start_time,start_station_id,start_station_name,end_station_id,end_station_name,duration_minutes
0,4098766,24 Hour Walk Up Pass,306,classic,2015-03-12 22:20:09+00:00,2546,ACC - West & 12th Street,2546,ACC - West & 12th Street,47
1,4073980,24 Hour Walk Up Pass,24,classic,2015-03-10 16:10:57+00:00,2545,ACC - Rio Grande & 12th,2546,ACC - West & 12th Street,24
2,4055367,24 Hour Walk Up Pass,862,classic,2015-03-07 19:55:41+00:00,2536,Waller & 6th St.,2568,East 11th/Victory Grill,8
3,4009457,Local365,142,classic,2015-02-27 11:21:15+00:00,2823,East 5th/Broadway @ Capital Metro HQ,2536,Waller & 6th St.,13
4,3988275,24 Hour Walk Up Pass,440,classic,2015-02-21 21:33:51+00:00,2546,ACC - West & 12th Street,2546,ACC - West & 12th Street,45
...,...,...,...,...,...,...,...,...,...,...
2271148,32428108,Local31,16828,electric,2024-02-06 23:49:25+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,22
2271149,32587422,Explorer,21884,electric,2024-02-27 22:25:33+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,2
2271150,32490790,Student Membership,16276,electric,2024-02-15 15:10:24+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,86
2271151,32494577,Student Membership,18564,electric,2024-02-15 23:43:45+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,482
2271152,32503143,Student Membership,22581,electric,2024-02-17 13:49:15+00:00,7189,28th/Rio Grande,7189,28th/Rio Grande,10

In [74]:
# Membuat query sesuai instruksi
query_5 = """
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE
  bike_id IS NOT NULL
  AND duration_minutes > 1000
"""

query_job5 = client.query(query_5)
result = query_job5.result().to_dataframe()
print(result)

       trip_id       subscriber_type bike_id bike_type  \
0     26051427              Explorer   22599  electric
1     25989880              Local365   21523  electric
2     25985609       Pay-as-you-ride   16333  electric
3     26987185              Local365   21698  electric
4     26658639  24 Hour Walk Up Pass   21712  electric
...        ...                   ...     ...       ...
3718  30934296    Student Membership     278   classic
3719  33143988              Explorer   19935  electric
3720  29850211              Explorer   19432  electric
3721  28844045    Student Membership   21485  electric
3722  28893573    Student Membership      57   classic

                    start_time  start_station_id    start_station_name  \
0    2022-02-20 11:33:34+00:00              3293   East 2nd/Pedernales
1    2022-02-07 16:44:17+00:00              3294            6th/Lavaca
2    2022-02-06 16:39:17+00:00              2569  East 11th/San Marcos
3    2022-06-22 16:56:26+00:00              7186      One Texas Center
4    2022-05-13 11:43:54+00:00              7187   South Congress/Mary
...                        ...               ...                   ...
3718 2023-09-10 14:42:32+00:00              7189       28th/Rio Grande
3719 2024-04-24 13:03:40+00:00              7189       28th/Rio Grande
3720 2023-06-08 15:05:44+00:00              7189       28th/Rio Grande
3721 2023-02-06 16:48:32+00:00              7189       28th/Rio Grande
3722 2023-02-15 15:34:29+00:00              7189       28th/Rio Grande

     end_station_id                      end_station_name  duration_minutes
0              2565                           6th/Trinity              2635
1              2823  East 5th/Broadway @ Capital Metro HQ              1099
2              4052                     Rosewood/Angelina              1103
3              7186                      One Texas Center              1019
4              7187                   South Congress/Mary              1515
...             ...                                   ...               ...
3718           7189                       28th/Rio Grande              2516
3719           7189                       28th/Rio Grande              1130
3720           7189                       28th/Rio Grande              1097
3721           7189                            22nd/Pearl              1092
3722           7189                       28th/Rio Grande              1209

[3723 rows x 10 columns]

### **Filter trips where the `trip_id` is "`Walk Up`" and the `end_station_name`  is "`Stolen`"**

In [86]:
# Membuat query sesuai instruksi
query_6 = """
SELECT *
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`
WHERE
  subscriber_type = 'Walk Up' AND end_station_name = 'Stolen'
"""

query_job6 = client.query(query_6)
result = query_job6.result().to_dataframe()
print(result)

    trip_id subscriber_type bike_id bike_type                start_time  \
0  16898448         Walk Up    1857   classic 2018-03-18 22:51:20+00:00
1  16863172         Walk Up    1795   classic 2018-03-14 21:23:26+00:00
2  17151360         Walk Up    1899   classic 2018-04-21 15:29:10+00:00
3  13555129         Walk Up     578   classic 2017-01-27 01:35:26+00:00
4  13564817         Walk Up     393   classic 2017-01-28 04:57:28+00:00
5  11712091         Walk Up     327   classic 2016-09-02 06:37:15+00:00
6  11714202         Walk Up     122   classic 2016-09-02 09:00:56+00:00
7  13857913         Walk Up     135   classic 2017-02-26 14:32:45+00:00

   start_station_id                                 start_station_name  \
0              2501                                        5th & Bowie
1              2542                                     Plaza Saltillo
2              2563                             Davis at Rainey Street
3              2498            Convention Center / 4th St. @ MetroRail
4              2561  State Capitol Visitors Garage @ San Jacinto & ...
5              2565                               Trinity & 6th Street
6              2565                               Trinity & 6th Street
7              2566                      Pfluger Bridge @ W 2nd Street

  end_station_id end_station_name  duration_minutes
0           None           Stolen              3806
1           None           Stolen              2529
2           None           Stolen              4302
3           None           Stolen              5189
4           None           Stolen              4833
5           None           Stolen              6118
6           None           Stolen              5974
7           None           Stolen              1404